version: '3.8'

services:
  libraryPostgres:
    image: postgres:12.3
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library-admin
      POSTGRES_PASSWORD: library-admin-secret
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
networks:
  default:
    external: false
    name: library
